### ISSUE TITLE
Creating multiple databases using this module

### ISSUE THREAD

**Issue by amit** [Azure/terraform-azurerm-database#6]
I was trying to use this module to create 3 SQL databases and when applying it, I get the following error: 

 `'Failed': Code="NameAlreadyExists" Message="The name 'acctsqlsvr' already exists.`

Is there any way to override the name parameter? Looking at https://github.com/Azure/terraform-azurerm-database/blob/master/main.tf#L26 it does not seem like it.

**Comment by JunyiYi** [comment]
I believe this issue is fixed by the pull request above.
